[package]
name = "distributed-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.1"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.2"
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_6"] }

[build-dependencies]
tonic-build = "0.10.2"

# gRPC test server binary
[[bin]]
name = "voting-server"
path = "src/voting/server.rs"

# gRPC test client binary
[[bin]]
name = "voting-client"
path = "src/voting/client.rs"

# gRPC test client binary
[[bin]]
name = "gui"
path = "src/gui/gui.rs"
